name: Deploy to gh-pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build app
        run: |
          npm install
          npm run build

      - name: Copy output to tmp folder
        run: cp -r ./public/ ./tmp

      - name: Checkout gh-pages
        run: |
          git fetch origin
          git checkout --track origin/gh-pages

      - name: Overwrite older build and remove tmp folder
        run: |
          cd tmp
          cp -r ./ ../
          cd ..
          rm -r ./tmp

      - name: Commit and push new build
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Automated build"
          git push
